// api/random.js

const express = require('express');
const cors = require('cors');  // Import the CORS package

const app = express();

// Use CORS middleware to allow all origins (or you can specify an origin)
app.use(cors());

const { generateRandomAge, getRandomElement } = require('../utils/randomGenerator');

// Data arrays
// const objArray = [
//   { firstname: 'Ahsan', gender: '', country: 'pk' },
//   { firstname: 'Tahir', gender: '', country: 'pk' },
//   { firstname: 'Khawar', gender: '', country: 'pk' },
//   { firstname: 'ali', gender: '', country: 'pk' },
//   { firstname: 'nasir', gender: '', country: 'pk' },
//   { firstname: 'Mohammad', gender: '', country: 'pk' },
// ];



const objArray = [
  { firstname: 'Ayesha', gender: 'F', country: 'pk' },
  { firstname: 'Fatima', gender: 'F', country: 'pk' },
  { firstname: 'Zainab', gender: 'F', country: 'pk' },
  { firstname: 'Maryam', gender: 'F', country: 'pk' },
  { firstname: 'Hira', gender: 'F', country: 'pk' },
  { firstname: 'Iqra', gender: 'F', country: 'pk' },
  { firstname: 'Laiba', gender: 'F', country: 'pk' },
  { firstname: 'Areeba', gender: 'F', country: 'pk' },
  { firstname: 'Maham', gender: 'F', country: 'pk' },
  { firstname: 'Noor', gender: 'F', country: 'pk' },
  { firstname: 'Aleena', gender: 'F', country: 'pk' },
  { firstname: 'Anum', gender: 'F', country: 'pk' },
  { firstname: 'Sana', gender: 'F', country: 'pk' },
  { firstname: 'Amna', gender: 'F', country: 'pk' },
  { firstname: 'Mehwish', gender: 'F', country: 'pk' },
  { firstname: 'Kinza', gender: 'F', country: 'pk' },
  { firstname: 'Aiman', gender: 'F', country: 'pk' },
  { firstname: 'Minal', gender: 'F', country: 'pk' },
  { firstname: 'Yusra', gender: 'F', country: 'pk' },
  { firstname: 'Hania', gender: 'F', country: 'pk' },
  { firstname: 'Rimsha', gender: 'F', country: 'pk' },
  { firstname: 'Eshal', gender: 'F', country: 'pk' },
  { firstname: 'Ifrah', gender: 'F', country: 'pk' },
  { firstname: 'Sadia', gender: 'F', country: 'pk' },
  { firstname: 'Nimra', gender: 'F', country: 'pk' },
  { firstname: 'Bushra', gender: 'F', country: 'pk' },
  { firstname: 'Fiza', gender: 'F', country: 'pk' },
  { firstname: 'Areej', gender: 'F', country: 'pk' },
  { firstname: 'Sehrish', gender: 'F', country: 'pk' },
  { firstname: 'Nida', gender: 'F', country: 'pk' },
  { firstname: 'Sidra', gender: 'F', country: 'pk' },
  { firstname: 'Komal', gender: 'F', country: 'pk' },
  { firstname: 'Nashwa', gender: 'F', country: 'pk' },
  { firstname: 'Tania', gender: 'F', country: 'pk' },
  { firstname: 'Shehla', gender: 'F', country: 'pk' },
  { firstname: 'Sumaira', gender: 'F', country: 'pk' },
  { firstname: 'Shazia', gender: 'F', country: 'pk' },
  { firstname: 'Rabia', gender: 'F', country: 'pk' },
  { firstname: 'Huma', gender: 'F', country: 'pk' },
  { firstname: 'Neha', gender: 'F', country: 'pk' },
  { firstname: 'Alina', gender: 'F', country: 'pk' },
  { firstname: 'Nayab', gender: 'F', country: 'pk' },
  { firstname: 'Mahnoor', gender: 'F', country: 'pk' },
  { firstname: 'Zoya', gender: 'F', country: 'pk' },
  { firstname: 'Sahar', gender: 'F', country: 'pk' },
  { firstname: 'Farah', gender: 'F', country: 'pk' },
  { firstname: 'Asmara', gender: 'F', country: 'pk' },
  { firstname: 'Afshan', gender: 'F', country: 'pk' },
  { firstname: 'Tuba', gender: 'F', country: 'pk' },
  { firstname: 'Fariha', gender: 'F', country: 'pk' },
  { firstname: 'Tooba', gender: 'F', country: 'pk' },
  { firstname: 'Sundas', gender: 'F', country: 'pk' },
  { firstname: 'Sobia', gender: 'F', country: 'pk' },
  { firstname: 'Tehmina', gender: 'F', country: 'pk' },
  { firstname: 'Nazia', gender: 'F', country: 'pk' },
  { firstname: 'Uzma', gender: 'F', country: 'pk' },
  { firstname: 'Khadija', gender: 'F', country: 'pk' },
  { firstname: 'Hafsa', gender: 'F', country: 'pk' },
  { firstname: 'Samina', gender: 'F', country: 'pk' },
  { firstname: 'Shaista', gender: 'F', country: 'pk' },
  { firstname: 'Zulekha', gender: 'F', country: 'pk' },
  { firstname: 'Asma', gender: 'F', country: 'pk' },
  { firstname: 'Javeria', gender: 'F', country: 'pk' },
  { firstname: 'Aqsa', gender: 'F', country: 'pk' },
  { firstname: 'Aleezay', gender: 'F', country: 'pk' },
  { firstname: 'Kiran', gender: 'F', country: 'pk' },
  { firstname: 'Haniah', gender: 'F', country: 'pk' },
  { firstname: 'Shanzay', gender: 'F', country: 'pk' },
  { firstname: 'Eman', gender: 'F', country: 'pk' },
  { firstname: 'Areeha', gender: 'F', country: 'pk' },
  { firstname: 'Rida', gender: 'F', country: 'pk' },
  { firstname: 'Inaya', gender: 'F', country: 'pk' },
  { firstname: 'Fareeha', gender: 'F', country: 'pk' },
  { firstname: 'Mishal', gender: 'F', country: 'pk' },
  { firstname: 'Izza', gender: 'F', country: 'pk' },
  { firstname: 'Aleeza', gender: 'F', country: 'pk' },
  { firstname: 'Samar', gender: 'F', country: 'pk' },
  { firstname: 'Mahira', gender: 'F', country: 'pk' },
  { firstname: 'Najma', gender: 'F', country: 'pk' },
  { firstname: 'Tahira', gender: 'F', country: 'pk' },
  { firstname: 'Nargis', gender: 'F', country: 'pk' },
  { firstname: 'Shagufta', gender: 'F', country: 'pk' },
  { firstname: 'Zeenat', gender: 'F', country: 'pk' },
  { firstname: 'Roohi', gender: 'F', country: 'pk' },
  { firstname: 'Asiya', gender: 'F', country: 'pk' },
  { firstname: 'Samra', gender: 'F', country: 'pk' },
  { firstname: 'Nashit', gender: 'F', country: 'pk' },
  { firstname: 'Lubna', gender: 'F', country: 'pk' },
  { firstname: 'Rameeza', gender: 'F', country: 'pk' },
  { firstname: 'Fakhra', gender: 'F', country: 'pk' },
  { firstname: 'Sajeela', gender: 'F', country: 'pk' },
  { firstname: 'Ghazala', gender: 'F', country: 'pk' },
  { firstname: 'Tanveer', gender: 'F', country: 'pk' },
  { firstname: 'Zakia', gender: 'F', country: 'pk' },
  { firstname: 'Salma', gender: 'F', country: 'pk' },
  { firstname: 'Shakeela', gender: 'F', country: 'pk' },
  { firstname: 'Rahat', gender: 'F', country: 'pk' },
  { firstname: 'Shamim', gender: 'F', country: 'pk' },
  { firstname: 'Shaheen', gender: 'F', country: 'pk' },
  { firstname: 'Haleema', gender: 'F', country: 'pk' },
  { firstname: 'Rukhsana', gender: 'F', country: 'pk' },
  { firstname: 'Parveen', gender: 'F', country: 'pk' },
  { firstname: 'Zubaida', gender: 'F', country: 'pk' },
  { firstname: 'Nighat', gender: 'F', country: 'pk' },
  { firstname: 'Husna', gender: 'F', country: 'pk' },
  { firstname: 'Tabassum', gender: 'F', country: 'pk' },
  { firstname: 'Jameela', gender: 'F', country: 'pk' },
  { firstname: 'Anila', gender: 'F', country: 'pk' },
  { firstname: 'Sobia', gender: 'F', country: 'pk' },
  { firstname: 'Fouzia', gender: 'F', country: 'pk' },
  { firstname: 'Bisma', gender: 'F', country: 'pk' },
  { firstname: 'Wajiha', gender: 'F', country: 'pk' },
  { firstname: 'Mehnaz', gender: 'F', country: 'pk' },
  { firstname: 'Sumbul', gender: 'F', country: 'pk' },
  { firstname: 'Zarqa', gender: 'F', country: 'pk' },
  { firstname: 'Tanzeela', gender: 'F', country: 'pk' },
  { firstname: 'Iffat', gender: 'F', country: 'pk' },
  { firstname: 'Asifa', gender: 'F', country: 'pk' },
  { firstname: 'Lubaba', gender: 'F', country: 'pk' },
  { firstname: 'Quratulain', gender: 'F', country: 'pk' },
  { firstname: 'Nashrah', gender: 'F', country: 'pk' },
  { firstname: 'Arooj', gender: 'F', country: 'pk' },
  { firstname: 'Minahil', gender: 'F', country: 'pk' },
  { firstname: 'Samarah', gender: 'F', country: 'pk' },
  { firstname: 'Ayra', gender: 'F', country: 'pk' },
  { firstname: 'Yumna', gender: 'F', country: 'pk' },
  { firstname: 'Nawal', gender: 'F', country: 'pk' },
  { firstname: 'Mahgul', gender: 'F', country: 'pk' },
  { firstname: 'Fajar', gender: 'F', country: 'pk' },
  { firstname: 'Aleesa', gender: 'F', country: 'pk' },
  { firstname: 'Zohra', gender: 'F', country: 'pk' },
  { firstname: 'Meera', gender: 'F', country: 'pk' },
  { firstname: 'Neelum', gender: 'F', country: 'pk' },
  { firstname: 'Sehr', gender: 'F', country: 'pk' },
  { firstname: 'Mahvish', gender: 'F', country: 'pk' },
  { firstname: 'Rameen', gender: 'F', country: 'pk' },
  { firstname: 'Shiza', gender: 'F', country: 'pk' },
  { firstname: 'Emaan', gender: 'F', country: 'pk' },
  { firstname: 'Aimanat', gender: 'F', country: 'pk' },
  { firstname: 'Nimrah', gender: 'F', country: 'pk' },
  { firstname: 'Madiha', gender: 'F', country: 'pk' },
  { firstname: 'Arisha', gender: 'F', country: 'pk' },
  { firstname: 'Laraib', gender: 'F', country: 'pk' },
  { firstname: 'Namrah', gender: 'F', country: 'pk' },
  { firstname: 'Imaan', gender: 'F', country: 'pk' },
  { firstname: 'Haleema', gender: 'F', country: 'pk' },
  { firstname: 'Zimal', gender: 'F', country: 'pk' },
  { firstname: 'Inaaya', gender: 'F', country: 'pk' },
  { firstname: 'Rania', gender: 'F', country: 'pk' },
  { firstname: 'Nashita', gender: 'F', country: 'pk' },
  { firstname: 'Sumaiya', gender: 'F', country: 'pk' },
  { firstname: 'Jana', gender: 'F', country: 'pk' },
  { firstname: 'Nayla', gender: 'F', country: 'pk' },
  { firstname: 'Dua', gender: 'F', country: 'pk' },
  { firstname: 'Farzana', gender: 'F', country: 'pk' },
  { firstname: 'Shamaila', gender: 'F', country: 'pk' },
  { firstname: 'Husna', gender: 'F', country: 'pk' },
  { firstname: 'Yasmeen', gender: 'F', country: 'pk' },
  { firstname: 'Ambar', gender: 'F', country: 'pk' },
  { firstname: 'Ramsha', gender: 'F', country: 'pk' },
  { firstname: 'Fahmida', gender: 'F', country: 'pk' },
  { firstname: 'Qudsia', gender: 'F', country: 'pk' },
  { firstname: 'Tazeen', gender: 'F', country: 'pk' },
  { firstname: 'Armeena', gender: 'F', country: 'pk' },
  { firstname: 'Neha', gender: 'F', country: 'pk' },
  { firstname: 'Aneela', gender: 'F', country: 'pk' },
  { firstname: 'Ruqayya', gender: 'F', country: 'pk' },
  { firstname: 'Salima', gender: 'F', country: 'pk' },
  { firstname: 'Kanwal', gender: 'F', country: 'pk' },
  { firstname: 'Sameera', gender: 'F', country: 'pk' },
  { firstname: 'Haniyah', gender: 'F', country: 'pk' },
  { firstname: 'Nayyara', gender: 'F', country: 'pk' },
  { firstname: 'Wardah', gender: 'F', country: 'pk' },
  { firstname: 'Shabana', gender: 'F', country: 'pk' },
  { firstname: 'Fariyal', gender: 'F', country: 'pk' },
  { firstname: 'Mishbah', gender: 'F', country: 'pk' },
  { firstname: 'Nazish', gender: 'F', country: 'pk' },
  { firstname: 'Shumaila', gender: 'F', country: 'pk' },
  { firstname: 'Najia', gender: 'F', country: 'pk' },
  { firstname: 'Rubina', gender: 'F', country: 'pk' },
  { firstname: 'Sabeen', gender: 'F', country: 'pk' },
  { firstname: 'Noreen', gender: 'F', country: 'pk' },
  { firstname: 'Afifa', gender: 'F', country: 'pk' },
  { firstname: 'Sadia', gender: 'F', country: 'pk' },
  { firstname: 'Jannat', gender: 'F', country: 'pk' },
  { firstname: 'Mahira', gender: 'F', country: 'pk' },
  { firstname: 'Amber', gender: 'F', country: 'pk' },
  { firstname: 'Shafia', gender: 'F', country: 'pk' },
  { firstname: 'Aqleem', gender: 'F', country: 'pk' },
  { firstname: 'Fareeda', gender: 'F', country: 'pk' },
  { firstname: 'Mahrukh', gender: 'F', country: 'pk' },
  { firstname: 'Almas', gender: 'F', country: 'pk' },
  { firstname: 'Samrah', gender: 'F', country: 'pk' },
  { firstname: 'Nooria', gender: 'F', country: 'pk' },
  { firstname: 'Tamanna', gender: 'F', country: 'pk' },
  { firstname: 'Batool', gender: 'F', country: 'pk' },
  { firstname: 'Aabroo', gender: 'F', country: 'pk' },
  { firstname: 'Laila', gender: 'F', country: 'pk' },
  { firstname: 'Zinia', gender: 'F', country: 'pk' },
  { firstname: 'Sundus', gender: 'F', country: 'pk' },
  { firstname: 'Gul', gender: 'F', country: 'pk' },
  { firstname: 'Azra', gender: 'F', country: 'pk' },
  { firstname: 'Meher', gender: 'F', country: 'pk' },
  { firstname: 'Saher', gender: 'F', country: 'pk' },
  { firstname: 'Mubashara', gender: 'F', country: 'pk' },
  { firstname: 'Yumna', gender: 'F', country: 'pk' },
  { firstname: 'Naureen', gender: 'F', country: 'pk' },
  { firstname: 'Saniya', gender: 'F', country: 'pk' },
  { firstname: 'Zakia', gender: 'F', country: 'pk' },
  { firstname: 'Hajra', gender: 'F', country: 'pk' },
  { firstname: 'Muzna', gender: 'F', country: 'pk' },
  { firstname: 'Suhana', gender: 'F', country: 'pk' },
  { firstname: 'Reema', gender: 'F', country: 'pk' },
  { firstname: 'Sajeela', gender: 'F', country: 'pk' },
  { firstname: 'Zarmeen', gender: 'F', country: 'pk' },
  { firstname: 'Zaib', gender: 'F', country: 'pk' },
  { firstname: 'Bakhtawar', gender: 'F', country: 'pk' }
];


const surnameArray = ['Khan',
  'Choudhry',
  'Siddiqui',
  'Hussain',
  'Ahmed',
  'Ali',
  'Raza',
  'Bilal',
  'Malik',
  'Qureshi',
  'Farooq',
  'Sheikh',
  'Abbasi',
  'Javed',
  'Shah',
  'Rehman',
  'Zahid',
  'Iqbal',
  'Latif',
  'Aslam',
  'Nawaz',
  'Butt',
  'Ansari',
  'Yousaf',
  'Mirza',
  'Tariq',
  'Nadeem',
  'Zaman',
  'Sajjad',
  'Hameed',
  'Javaid',
  'Rafique',
  'Mehmood',
  'Saeed',
  'Akhtar',
  'Rashid',
  'Shafiq',
  'Nisar',
  'Rauf',
  'Saleem',
  'Shahid',
  'Waheed',
  'Kamran',
  'Imran',
  'Faisal',
  'Usman',
  'Arshad',
  'Ilyas',

  // Common Castes/Surnames
  'Awan',
  'Gondal',
  'Rajput',
  'Gujjar',
  'Arain',
  'Mughal',
  'Syed',
  'Shamsi',
  'Bukhari',
  'Hashmi',
  'Gilani',
  'Jutt',
  'Tarar',
  'Cheema',
  'Bhatti',
  'Warraich',
  'Dogar',
  'Toor',
  'Randhawa',
  'Soomro',
  'Junejo',
  'Memon',
  'Laghari',
  'Chishti',
  'Noon',
  'Rind',
  'Mazari',
  'Bugti',
  'Jamali',
  'Khattak',
  'Afridi',
  'Yousafzai',
  'Orakzai',
  'Swati',
  'Shirani',
  'Durrani',
  'Gabol',
  'Baloch',
  'Brohi',
  'Talpur',
  'Alvi',
  'Barlas',
  'Sherazi',
  'Niazi',
  'Mian',
  'Shamsher',
  'Turi',
  'Agha'];

// Handle the request for random data
const getRandomData = (req, res) => {
  const randomObj = getRandomElement(objArray);
  const randomSurname = getRandomElement(surnameArray);
  const randomAge = generateRandomAge();

  const responseObj = {
    ...randomObj,
    surname: randomSurname,
    age: randomAge,
  };

  res.json(responseObj);
};

// Vercel function handler
module.exports = async (req, res) => {
  if (req.method === 'GET' && req.url === '/api/random') {
    getRandomData(req, res);
  } else {
    res.status(404).send('Not Found');
  }
};
